spring.application.name=hospital-management-system

server.port=${PORT:8080}

spring.datasource.url=jdbc:postgresql://dpg-d8a20537uimc73a0li90-a/hospitaldb_yhz0
spring.datasource.username=hospitaldb_yhz0_user
spring.datasource.password=fsbuFhVeB8DNhh9xt94Jt2uQ9YK7Jm56

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect